# coding=utf-8
# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.net.proto2.python.public import descriptor
from google.net.proto2.python.public import message
from google.net.proto2.python.public import reflection
from google.net.proto2.proto import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='Backpack.proto',
  package='',
  serialized_pb='\n\x0e\x42\x61\x63kpack.proto\":\n\x08\x42\x61\x63kpack\x12\x11\n\ttimestamp\x18\x01 \x01(\x05\x12\x1b\n\x04item\x18\x02 \x03(\x0b\x32\r.BackpackItem\",\n\x0c\x42\x61\x63kpackItem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\x42-\n\x1c\x63om.kloomba.app.api.protobufB\rBackpackProto')




_BACKPACK = descriptor.Descriptor(
  name='Backpack',
  full_name='Backpack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='timestamp', full_name='Backpack.timestamp', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='item', full_name='Backpack.item', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=18,
  serialized_end=76,
)


_BACKPACKITEM = descriptor.Descriptor(
  name='BackpackItem',
  full_name='BackpackItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='BackpackItem.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='amount', full_name='BackpackItem.amount', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=78,
  serialized_end=122,
)

_BACKPACK.fields_by_name['item'].message_type = _BACKPACKITEM
DESCRIPTOR.message_types_by_name['Backpack'] = _BACKPACK
DESCRIPTOR.message_types_by_name['BackpackItem'] = _BACKPACKITEM

class Backpack(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BACKPACK
  
  # @@protoc_insertion_point(class_scope:Backpack)

class BackpackItem(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BACKPACKITEM
  
  # @@protoc_insertion_point(class_scope:BackpackItem)

# @@protoc_insertion_point(module_scope)
