# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.net.proto2.python.public import descriptor
from google.net.proto2.python.public import message
from google.net.proto2.python.public import reflection
from google.net.proto2.proto import descriptor_pb2
# @@protoc_insertion_point(imports)


import Flowerbed_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='BookmarkList.proto',
  package='',
  serialized_pb='\n\x12\x42ookmarkList.proto\x1a\x0f\x46lowerbed.proto\"@\n\x0c\x42ookmarkList\x12\x11\n\ttimestamp\x18\x01 \x01(\x05\x12\x1d\n\tflowerbed\x18\x02 \x03(\x0b\x32\n.FlowerbedB1\n\x1c\x63om.kloomba.app.api.protobufB\x11\x42ookmarkListProto')




_BOOKMARKLIST = descriptor.Descriptor(
  name='BookmarkList',
  full_name='BookmarkList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='timestamp', full_name='BookmarkList.timestamp', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='flowerbed', full_name='BookmarkList.flowerbed', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=39,
  serialized_end=103,
)

_BOOKMARKLIST.fields_by_name['flowerbed'].message_type = Flowerbed_pb2._FLOWERBED
DESCRIPTOR.message_types_by_name['BookmarkList'] = _BOOKMARKLIST

class BookmarkList(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BOOKMARKLIST
  
  # @@protoc_insertion_point(class_scope:BookmarkList)

# @@protoc_insertion_point(module_scope)
