# coding=utf-8
# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.net.proto2.python.public import descriptor
from google.net.proto2.python.public import message
from google.net.proto2.python.public import reflection
from google.net.proto2.proto import descriptor_pb2
# @@protoc_insertion_point(imports)


import Backpack_pb2
import Flowerbed_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='FlowerbedAdd.proto',
  package='',
  serialized_pb='\n\x12\x46lowerbedAdd.proto\x1a\x0e\x42\x61\x63kpack.proto\x1a\x0f\x46lowerbed.proto\"]\n\x0c\x46lowerbedAdd\x12\x11\n\ttimestamp\x18\x01 \x01(\x05\x12\x1d\n\tflowerbed\x18\x02 \x01(\x0b\x32\n.Flowerbed\x12\x1b\n\x08\x62\x61\x63kpack\x18\x03 \x01(\x0b\x32\t.BackpackB1\n\x1c\x63om.kloomba.app.api.protobufB\x11\x46lowerbedAddProto')




_FLOWERBEDADD = descriptor.Descriptor(
  name='FlowerbedAdd',
  full_name='FlowerbedAdd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='timestamp', full_name='FlowerbedAdd.timestamp', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='flowerbed', full_name='FlowerbedAdd.flowerbed', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='backpack', full_name='FlowerbedAdd.backpack', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=55,
  serialized_end=148,
)

_FLOWERBEDADD.fields_by_name['flowerbed'].message_type = Flowerbed_pb2._FLOWERBED
_FLOWERBEDADD.fields_by_name['backpack'].message_type = Backpack_pb2._BACKPACK
DESCRIPTOR.message_types_by_name['FlowerbedAdd'] = _FLOWERBEDADD

class FlowerbedAdd(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FLOWERBEDADD
  
  # @@protoc_insertion_point(class_scope:FlowerbedAdd)

# @@protoc_insertion_point(module_scope)
