# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.net.proto2.python.public import descriptor
from google.net.proto2.python.public import message
from google.net.proto2.python.public import reflection
# @@protoc_insertion_point(imports)


import Possession_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='PossessionList.proto',
  package='',
  serialized_pb='\n\x14PossessionList.proto\x1a\x10Possession.proto\"D\n\x0ePossessionList\x12\x11\n\ttimestamp\x18\x01 \x01(\x05\x12\x1f\n\npossession\x18\x02 \x03(\x0b\x32\x0b.PossessionB3\n\x1c\x63om.kloomba.app.api.protobufB\x13PossessionListProto')




_POSSESSIONLIST = descriptor.Descriptor(
  name='PossessionList',
  full_name='PossessionList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='timestamp', full_name='PossessionList.timestamp', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='possession', full_name='PossessionList.possession', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=42,
  serialized_end=110,
)

_POSSESSIONLIST.fields_by_name['possession'].message_type = Possession_pb2._POSSESSION
DESCRIPTOR.message_types_by_name['PossessionList'] = _POSSESSIONLIST

class PossessionList(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _POSSESSIONLIST
  
  # @@protoc_insertion_point(class_scope:PossessionList)

# @@protoc_insertion_point(module_scope)
