application: kloomba-app
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "7d"

handlers:
- url: /(login|flowerbed|possession|bookmark).*
  script: main.app
  login: required

- url: /favicon\.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: /.*
  script: main.app

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?.*\.iml
- ^(.*/)?.*/.idea/.*
